//***********************App*************************
export const GET_THEME_LIST_REQUEST = 'GET_THEME_LIST_REQUEST';
export const GET_THEME_LIST_SUCCESS = 'GET_THEME_LIST_SUCCESS';
export const GET_THEME_LIST_FAILURE = 'GET_THEME_LIST_FAILURE';

// *****************Chat Module Types
//Get All Conversatuin
export const GET_ALL_CONVERSATION_REQUEST = 'GET_ALL_CONVERSATION_REQUEST';
export const GET_ALL_CONVERSATION_SUCCESS = 'GET_ALL_CONVERSATION_SUCCESS';
export const GET_ALL_CONVERSATION_FAILURE = 'GET_ALL_CONVERSATION_FAILURE';

//Read All Messages
export const READ_ALL_MESSAGES_REQUEST = 'READ_ALL_MESSAGES_REQUEST';
export const READ_ALL_MESSAGES_SUCCESS = 'READ_ALL_MESSAGES_SUCCESS';
export const READ_ALL_MESSAGES_FAILURE = 'READ_ALL_MESSAGES_FAILURE';

//Create Conversatuin
export const CREATE_CONVERSATION_REQUEST = 'CREATE_CONVERSATION_REQUEST';
export const CREATE_CONVERSATION_SUCCESS = 'CREATE_CONVERSATION_SUCCESS';
export const CREATE_CONVERSATION_FAILURE = 'CREATE_CONVERSATION_FAILURE';

//Get Conversatuin
export const GET_CONVERSATION_REQUEST = 'GET_CONVERSATION_REQUEST';
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS';
export const GET_CONVERSATION_FAILURE = 'GET_CONVERSATION_FAILURE';

//Create Conversatuin
export const DELETE_CONVERSATION_REQUEST = 'DELETE_CONVERSATION_REQUEST';
export const DELETE_CONVERSATION_SUCCESS = 'DELETE_CONVERSATION_SUCCESS';
export const DELETE_CONVERSATION_FAILURE = 'DELETE_CONVERSATION_FAILURE';

//Send Message
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

//Get Message
export const GET_MESSAGE_REQUEST = 'GET_MESSAGE_REQUEST';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_FAILURE = 'GET_MESSAGE_FAILURE';

// ***********Chat Module

//Get All Burn Number
export const GET_BURN_NUMBERS_REQUEST = 'GET_BURN_NUMBERS_REQUEST';
export const GET_BURN_NUMBERS_SUCCESS = 'GET_BURN_NUMBERS_SUCCESS';
export const GET_BURN_NUMBERS_FAILURE = 'GET_BURN_NUMBERS_FAILURE';
//Burn Number
export const BURN_NUMBER_REQUEST = 'BURN_NUMBER_REQUEST';
export const BURN_NUMBER_SUCCESS = 'BURN_NUMBER_SUCCESS';
export const BURN_NUMBER_FAILURE = 'BURN_NUMBER_FAILURE';
//Delete Burn Number
export const DELETE_NUMBER_REQUEST = 'DELETE_NUMBER_REQUEST';
export const DELETE_NUMBER_SUCCESS = 'DELETE_NUMBER_SUCCESS';
export const DELETE_NUMBER_FAILURE = 'DELETE_NUMBER_FAILURE';

//***********************Settings*************************

//Check Connected Account
export const CHECK_CONNECTED_ACCOUNT_REQUEST =
  'CHECK_CONNECTED_ACCOUNT_REQUEST';
export const CHECK_CONNECTED_ACCOUNT_SUCCESS =
  'CHECK_CONNECTED_ACCOUNT_SUCCESS';

//Get Mutual Contacts
export const GET_MUTUAL_CONTACTS_REQUEST = 'GET_MUTUAL_CONTACTS_REQUEST';
export const GET_MUTUAL_CONTACTS_SUCCESS = 'GET_MUTUAL_CONTACTS_SUCCESS';
export const GET_MUTUAL_CONTACTS_FAILURE = 'GET_MUTUAL_CONTACTS_FAILURE';

//Get D Mutual Contacts
export const GET_DMUTUAL_CONTACTS_REQUEST = 'GET_DMUTUAL_CONTACTS_REQUEST';
export const GET_DMUTUAL_CONTACTS_SUCCESS = 'GET_DMUTUAL_CONTACTS_SUCCESS';
export const GET_DMUTUAL_CONTACTS_FAILURE = 'GET_DMUTUAL_CONTACTS_FAILURE';

//Get Bank LIST
export const GET_BANK_LIST_REQUEST = 'GET_BANK_LIST_REQUEST';
export const GET_BANK_LIST_SUCCESS = 'GET_BANK_LIST_SUCCESS';
export const GET_BANK_LIST_FAILURE = 'GET_BANK_LIST_FAILURE';

//Add Default Bank
export const ADD_DEFAULT_BANK_REQUEST = 'ADD_DEFAULT_BANK_REQUEST';
export const ADD_DEFAULT_BANK_SUCCESS = 'ADD_DEFAULT_BANK_SUCCESS';
export const ADD_DEFAULT_BANK_FAILURE = 'ADD_DEFAULT_BANK_FAILURE';

//Get Default Bank
export const GET_DEFAULT_BANK_REQUEST = 'GET_DEFAULT_BANK_REQUEST';
export const GET_DEFAULT_BANK_SUCCESS = 'GET_DEFAULT_BANK_SUCCESS';
export const GET_DEFAULT_BANK_FAILURE = 'GET_DEFAULT_BANK_FAILURE';

//Get CARD LIST
export const GET_CARD_LIST_REQUEST = 'GET_CARD_LIST_REQUEST';
export const GET_CARD_LIST_SUCCESS = 'GET_CARD_LIST_SUCCESS';
export const GET_CARD_LIST_FAILURE = 'GET_CARD_LIST_FAILURE';

//Add Default Card
export const ADD_DEFAULT_CARD_REQUEST = 'ADD_DEFAULT_CARD_REQUEST';
export const ADD_DEFAULT_CARD_SUCCESS = 'ADD_DEFAULT_CARD_SUCCESS';
export const ADD_DEFAULT_CARD_FAILURE = 'ADD_DEFAULT_CARD_FAILURE';

//Get Default Card
export const GET_DEFAULT_CARD_REQUEST = 'GET_DEFAULT_CARD_REQUEST';
export const GET_DEFAULT_CARD_SUCCESS = 'GET_DEFAULT_CARD_SUCCESS';
export const GET_DEFAULT_CARD_FAILURE = 'GET_DEFAULT_CARD_FAILURE';

//Payment Method
export const PAYMENT_METHOD_REQUEST = 'PAYMENT_METHOD_REQUEST';
export const PAYMENT_METHOD_SUCCESS = 'PAYMENT_METHOD_SUCCESS';

//Top Up Method
export const TOP_UP_ACCOUNT_REQUEST = 'TOP_UP_ACCOUNT_REQUEST';
export const TOP_UP_ACCOUNT_SUCCESS = 'TOP_UP_ACCOUNT_SUCCESS';
export const TOP_UP_ACCOUNT_FAILURE = 'TOP_UP_ACCOUNT_FAILURE';

//Withdraw Payment
export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_FAILURE = 'WITHDRAW_FAILURE';

//Transfer Method
export const TRANSFER_PAYMENT_REQUEST = 'TRANSFER_PAYMENT_REQUEST';
export const TRANSFER_PAYMENT_SUCCESS = 'TRANSFER_PAYMENT_SUCCESS';
export const TRANSFER_PAYMENT_FAILURE = 'TRANSFER_PAYMENT_FAILURE';

//ADD Bank
export const ADD_BANK_REQUEST = 'ADD_BANK_REQUEST';
export const ADD_BANK_SUCCESS = 'ADD_BANK_SUCCESS';
export const ADD_BANK_FAILURE = 'ADD_BANK_FAILURE';
//Deleted Bank
export const DELETE_BANK_REQUEST = 'DELETE_BANK_REQUEST';
export const DELETE_BANK_SUCCESS = 'DELETE_BANK_SUCCESS';
export const DELETE_BANK_FAILURE = 'DELETE_BANK_FAILURE';
//Edit Bank
export const EDIT_BANK_REQUEST = 'EDIT_BANK_REQUEST';
export const EDIT_BANK_SUCCESS = 'EDIT_BANK_SUCCESS';
export const EDIT_BANK_FAILURE = 'EDIT_BANK_FAILURE';

//ADD CARD
export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';
//Deleted Card
export const DELETE_CARD_REQUEST = 'DELETE_CARD_REQUEST';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE';
//Delete card
export const EDIT_CARD_REQUEST = 'EDIT_CARD_REQUEST';
export const EDIT_CARD_SUCCESS = 'EDIT_CARD_SUCCESS';
export const EDIT_CARD_FAILURE = 'EDIT_CARD_FAILURE';

//Set Checkout Data
export const SET_CHECKOUT_DATA_REQUEST = 'SET_CHECKOUT_DATA_REQUEST';
export const SET_CHECKOUT_DATA_SUCCESS = 'SET_CHECKOUT_DATA_SUCCESS';

//Pay With Debit
export const PAY_WITH_DEBIT_REQUEST = 'PAY_WITH_DEBIT_REQUEST';
export const PAY_WITH_DEBIT_SUCCESS = 'PAY_WITH_DEBIT_SUCCESS';
export const PAY_WITH_DEBIT_FAILURE = 'PAY_WITH_DEBIT_FAILURE';

//Pay With Google
export const PAY_WITH_SOCIAL_REQUEST = 'PAY_WITH_SOCIAL_REQUEST';
export const PAY_WITH_SOCIAL_SUCCESS = 'PAY_WITH_SOCIAL_SUCCESS';
export const PAY_WITH_SOCIAL_FAILURE = 'PAY_WITH_SOCIAL_FAILURE';

//Settings Types
export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAILURE = 'UPDATE_STATUS_FAILURE';

//***********************Contacts*************************
//ADD Contact
export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILURE = 'ADD_CONTACT_FAILURE';

//Edit Contact
export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';

//Set Checked Contact
export const CHECKED_CONTACT_REQUEST = 'CHECKED_CONTACT_REQUEST';
export const CHECKED_CONTACT_SUCCESS = 'CHECKED_CONTACT_SUCCESS';

//Remove Checked Contact
export const REMOVE_CONTACT_REQUEST = 'REMOVE_CONTACT_REQUEST';
export const REMOVE_CONTACT_SUCCESS = 'REMOVE_CONTACT_SUCCESS';

export const GET_GROUP_CONTACT_REQUEST = 'GET_GROUP_CONTACT_REQUEST';
export const GET_GROUP_CONTACT_SUCCESS = 'GET_GROUP_CONTACT_SUCCESS';
export const GET_GROUP_CONTACT_FAILURE = 'GET_GROUP_CONTACT_FAILURE';
//Add Group Contact
export const ADD_GROUP_CONTACT_REQUEST = 'ADD_GROUP_CONTACT_REQUEST';
export const ADD_GROUP_CONTACT_SUCCESS = 'ADD_GROUP_CONTACT_SUCCESS';
export const ADD_GROUP_CONTACT_FAILURE = 'ADD_GROUP_CONTACT_FAILURE';
//Edit Group Contact
export const EDIT_GROUP_CONTACT_REQUEST = 'EDIT_GROUP_CONTACT_REQUEST';
export const EDIT_GROUP_CONTACT_SUCCESS = 'EDIT_GROUP_CONTACT_SUCCESS';
export const EDIT_GROUP_CONTACT_FAILURE = 'EDIT_GROUP_CONTACT_FAILURE';
//Delete Group Contact
export const DELETE_GROUP_CONTACT_REQUEST = 'DELETE_GROUP_CONTACT_REQUEST';
export const DELETE_GROUP_CONTACT_SUCCESS = 'DELETE_GROUP_CONTACT_SUCCESS';
export const DELETE_GROUP_CONTACT_FAILURE = 'DELETE_GROUP_CONTACT_FAILURE';

//Remove Group Member
export const REMOVE_GROUP_MEMBER_REQUEST = 'REMOVE_GROUP_MEMBER_REQUEST';
export const REMOVE_GROUP_MEMBER_SUCCESS = 'REMOVE_GROUP_MEMBER_SUCCESS';
export const REMOVE_GROUP_MEMBER_FAILURE = 'REMOVE_GROUP_MEMBER_FAILURE';

//Get Groups
export const GET_GROUPS_REQUEST = 'GET_GROUPS_REQUEST';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAILURE = 'GET_GROUPS_FAILURE';

//List Contacts
export const LIST_CONTACT_REQUEST = 'LIST_CONTACT_REQUEST';
export const LIST_CONTACT_SUCCESS = 'LIST_CONTACT_SUCCESS';
export const LIST_CONTACT_FAILURE = 'LIST_CONTACT_FAILURE';
//Add to Favourite
export const ADD_TO_FAVOURITE_REQUEST = 'ADD_TO_FAVOURITE_REQUEST';
export const ADD_TO_FAVOURITE_SUCCESS = 'ADD_TO_FAVOURITE_SUCCESS';
export const ADD_TO_FAVOURITE_FAILURE = 'ADD_TO_FAVOURITE_FAILURE';
//Get Favourite
export const GET_FAVOURITE_REQUEST = 'GET_FAVOURITE_REQUEST';
export const GET_FAVOURITE_SUCCESS = 'GET_FAVOURITE_SUCCESS';
export const GET_FAVOURITE_FAILURE = 'GET_FAVOURITE_FAILURE';
//Delete Favourite
export const DELETE_FAVOURITE_REQUEST = 'DELETE_FAVOURITE_REQUEST';
export const DELETE_FAVOURITE_SUCCESS = 'DELETE_FAVOURITE_SUCCESS';
export const DELETE_FAVOURITE_FAILURE = 'DELETE_FAVOURITE_FAILURE';

//***********************Authentication************************* */
//Types for Login
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
//Types for Logout
export const LOGOUT_REQUEST_REQUEST = 'LOGOUT_REQUEST_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';
//Types for Social Login
export const SOCIAL_LOGIN_REQUEST_REQUEST = 'SOCIAL_LOGIN_REQUEST_REQUEST';
export const SOCIAL_LOGIN_REQUEST_SUCCESS = 'SOCIAL_LOGIN_REQUEST_SUCCESS';
export const SOCIAL_LOGIN_REQUEST_FAILURE = 'SOCIAL_LOGIN_REQUEST_FAILURE';
//Types for Sign up
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Save SignUp Data
export const SAVE_SIGNUP_DATA_REQUEST = 'SAVE_SIGNUP_DATA_REQUEST';
export const SAVE_SIGNUP_DATA_SUCCESS = 'SAVE_SIGNUP_DATA_SUCCESS';

//Types for OTP Verification
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

//Types for  forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//Types for  Resend OTP
export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

//Types for reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

//GET PROFILE
export const GET_PHONE_NUMBER_REQUEST = 'GET_PHONE_NUMBER_REQUEST';
export const GET_PHONE_NUMBER_SUCCESS = 'GET_PHONE_NUMBER_SUCCESS';
export const GET_PHONE_NUMBER_FAILURE = 'GET_PHONE_NUMBER_FAILURE';

//GET PROFILE
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

//UPDATE PROFILE
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

//Update Email
export const UPDATE_EMAIL_REQUEST = 'UPDATE_EMAIL_REQUEST';
export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS';
export const UPDATE_EMAIL_FAILURE = 'UPDATE_EMAIL_FAILURE';

export const SET_APP_THEME_REQUEST = 'SET_APP_THEME_REQUEST';
export const SET_APP_THEME_SUCCESS = 'SET_APP_THEME_SUCCESS';

export const SET_ITEM_DETAIL_REQUEST = 'SET_ITEM_DETAIL_REQUEST';
export const SET_ITEM_DETAIL_SUCCESS = 'SET_ITEM_DETAIL_SUCCESS';

export const SET_OPEN_TABS_REQUEST = 'SET_OPEN_TABS_REQUEST';
export const SET_OPEN_TABS_SUCCESS = 'SET_OPEN_TABS_SUCCESS';

//GET PRIVACY AND POLICY  SETTING
export const GET_PRIVACY_POLICY = 'GET_PRIVACY_POLICY';
export const GET_PRIVACY_POLICY_FAIL = 'GET_PRIVACY_POLICY_FAIL';
export const GET_PRIVACY_POLICY_PASS = 'GET_PRIVACY_POLICY_PASS';

//GET TERMS AND CONDITIONS SETTING
export const GET_TERMS_AND_CONDITIONS = 'GET_TERMS_AND_CONDITIONS';
export const GET_TERMS_AND_CONDITIONS_PASS = 'GET_TERMS_AND_CONDITIONS_PASS';
export const GET_TERMS_AND_CONDITIONS_FAIL = 'GET_TERMS_AND_CONDITIONS_FAIL';

//GET FAQS SETTING
export const GET_FAQS = 'GET_FAQS';
export const GET_FAQS_PASS = 'GET_FAQS_PASS';
export const GET_FAQS_FAIL = 'GET_FAQS_FAIL';

//GET SUPPORT
export const GET_SUPPORT = 'GET_SUPPORT';
export const GET_SUPPORT_PASS = 'GET_SUPPORT_PASS';
export const GET_SUPPORT_FAIL = 'GET_SUPPORT_FAIL';

//POST TICKET FOR SUPPORT
export const POST_TICKET = 'POST_TICKET';
export const POST_TICKET_PASS = 'POST_TICKET_PASS';
export const POST_TICKET_FAIL = 'POST_TICKET_FAIL';

//SET MESSAGES
export const SET_MESSAGE_REQUEST = 'SET_MESSAGE_REQUEST';
export const SET_MESSAGE_SUCCESS = 'SET_MESSAGE_SUCCESS';
export const SET_MESSAGE_FAILURE = 'SET_MESSAGE_FAILURE';

//SET MESSAGES
export const CURRENT_MESSAGE_REQUEST = 'CURRENT_MESSAGE_REQUEST';
export const CURRENT_MESSAGE_SUCCESS = 'CURRENT_MESSAGE_SUCCESS';
export const CURRENT_MESSAGE_FAILURE = 'CURRENT_MESSAGE_FAILURE';

//Stop Play

export const STOP_PLAY_REQUEST = 'STOP_PLAY_REQUEST';
export const STOP_PLAY_SUCCESS = 'STOP_PLAY_SUCCESS';

//Audio
export const SET_AUDIO_LOADING_REQUEST = 'SET_AUDIO_LOADING_REQUEST';
export const SET_AUDIO_LOADING_SUCCESS = 'SET_AUDIO_LOADING_SUCCESS';

//Set Duration
export const SET_AUDIO_DURATION_REQUEST = 'SET_AUDIO_DURATION_REQUEST';
export const SET_AUDIO_DURATION_SUCCESS = 'SET_AUDIO_DURATION_SUCCESS';

// Notifications
export const SAVE_FCM_TOKEN_REQUEST = 'SAVE_FCM_TOKEN_REQUEST';
export const SAVE_FCM_TOKEN_SUCCESS = 'SAVE_FCM_TOKEN_SUCCESS';
export const SAVE_FCM_TOKEN_FAILURE = 'SAVE_FCM_TOKEN_FAILURE';

//************************************ History *******************************

//Get Video Call History
export const GET_VIDEO_CALL_HISTORY = 'GET_VIDEO_CALL_HISTORY';
export const GET_VIDEO_CALL_HISTORY_SUCCESS = 'GET_VIDEO_CALL_HISTORY_SUCCESS';
export const GET_VIDEO_CALL_HISTORY_FAIL = ' GET_VIDEO_CALL_HISTORY_FAIL';

//Get Audio Call History
export const GET_AUDIO_CALL_HISTORY = 'GET_AUDIO_CALL_HISTORY';
export const GET_AUDIO_CALL_HISTORY_SUCCESS = 'GET_AUDIO_CALL_HISTORY_SUCCESS';
export const GET_AUDIO_CALL_HISTORY_FAIL = ' GET_AUDIO_CALL_HISTORY_FAIL';

//Get All CALL History

export const GET_ALL_CALL_HISTORY = 'GET_ALL_CALL_HISTORY';
export const GET_ALL_CALL_HISTORY_SUCCESS = ' GET_ALL_CALL_HISTORY_SUCCESS';
export const GET_ALL_CALL_HISTORY_FAIL = ' GET_ALL_CALL_HISTORY_FAIL';

//Blocke USer

export const BLOCK_USER = 'BLOCK_USER';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAIL = 'BLOCK_USER_FAIL';

// cLear All callLogs

export const CLEAR_ALL_CALL_LOGS = 'CLEAR_ALL_CALL_LOGS';
export const CLEAR_ALL_CALL_LOGS_SUCCESS = 'CLEAR_ALL_CALL_LOGS_SUCCESS';
export const CLEAR_ALL_CALL_LOGS_FAIL = 'CLEAR_ALL_CALL_LOGS_FAIL';

// cLear Specific call Logs

export const CLEAR_SPECIFIC_CALL_LOGS = 'CLEAR_SPECIFIC_CALL_LOGS';
export const CLEAR_SPECIFIC_LOGS_SUCCESS = 'CLEAR_SPECIFIC_CALL_LOGS_SUCCESS';
export const CLEAR_SPECIFIC_LOGS_FAIL = 'CLEAR_ALL_SPECIFIC_LOGS_FAIL';

// RECENT CALL LOGS

export const GET_RECENT_CALL_LOGS = 'GET_RECENT_CALL_LOGS';
export const GET_RECENT_CALL_LOGS_SUCCESS = 'GET_RECENT_CALL_LOGS_SUCCESS';
export const GET_RECENT_CALL_LOGS_FAIL = 'GET_RECENT_CALL_LOGS_FAIL';

//Calling Service

export const INITIALIZE_CALL_SERVICE_REQUEST =
  'INITIALIZE_CALL_SERVICE_REQUEST';
export const INITIALIZE_CALL_SERVICE_SUCCESS =
  'INITIALIZE_CALL_SERVICE_SUCCESS';
export const INITIALIZE_CALL_SERVICE_FAIL = 'INITIALIZE_CALL_SERVICE_FAIL';

export const DESTROY_CALL_SERVICE_REQUEST = 'DESTROY_CALL_SERVICE_REQUEST';
export const DESTROY_CALL_SERVICE_SUCCESS = 'DESTROY_CALL_SERVICE_SUCCESS';
export const DESTROY_CALL_SERVICE_FAIL = 'DESTROY_CALL_SERVICE_FAIL';

// Video Calling Service

export const INITIALIZE_VIDEO_CALL_SERVICE_REQUEST =
  'INITIALIZE_VIDEO_CALL_SERVICE_REQUEST';
export const INITIALIZE_VIDEO_CALL_SERVICE_SUCCESS =
  'INITIALIZE_VIDEO_CALL_SERVICE_SUCCESS';
export const INITIALIZE_VIDEO_CALL_SERVICE_FAIL =
  'INITIALIZE_VIDEO_CALL_SERVICE_FAIL';

export const DESTROY_VIDEO_CALL_SERVICE_REQUEST =
  'DESTROY_VIDEO_CALL_SERVICE_REQUEST';
export const DESTROY_VIDEO_CALL_SERVICE_SUCCESS =
  'DESTROY_VIDEO_CALL_SERVICE_SUCCESS';
export const DESTROY_VIDEO_CALL_SERVICE_FAIL =
  'DESTROY_VIDEO_CALL_SERVICE_FAIL';
// Transaction History

export const GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY';
export const GET_TRANSACTION_HISTORY_SUCCESS =
  'GET_TRANSACTION_HISTORY_SUCCESS';
export const GET_TRANSACTION_HISTORY_FAIL = 'GET_TRANSACTION_HISTORY_FAIL';

// *********************Group Call*****************
export const INITIATE_GROUP_VOICE_CALL_REQUEST =
  'INITIATE_GROUP_VOICE_CALL_REQUEST';
export const INITIATE_GROUP_VOICE_CALL_SUCCESS =
  'INITIATE_GROUP_VOICE_CALL_SUCCESS';
export const INITIATE_GROUP_VOICE_CALL_FAILURE =
  'INITIATE_GROUP_VOICE_CALL_FAILURE';

// Initiate Group Video call

export const INITIATE_GROUP_VIDEO_CALL_REQUEST =
  'INITIATE_GROUP_VIDEO_CALL_REQUEST';
export const INITIATE_GROUP_VIDEO_CALL_SUCCESS =
  'INITIATE_GROUP_VIDEO_CALL_SUCCESS';
export const INITIATE_GROUP_VIDEO_CALL_FAILURE =
  'INITIATE_GROUP_VIDEO_CALL_FAILURE';

// Destroy Group Call
export const DESTROY_GROUP_VOICE_CALL_REQUEST =
  'DESTROY_GROUP_VOICE_CALL_REQUEST';
export const DESTROY_GROUP_VOICE_CALL_SUCCESS =
  'DESTROY_GROUP_VOICE_CALL_SUCCESS';
export const DESTROY_GROUP_VOICE_CALL_FAILURE =
  'DESTROY_GROUP_VOICE_CALL_FAILURE';

// Destroy Video Group Call

export const DESTROY_GROUP_VIDEO_CALL_REQUEST =
  'DESTROY_GROUP_VIDEO_CALL_REQUEST';
export const DESTROY_GROUP_VIDEO_CALL_SUCCESS =
  'DESTROY_GROUP_VIDEO_CALL_SUCCESS';
export const DESTROY_GROUP_VIDEO_CALL_FAILURE =
  'DESTROY_GROUP_VIDEO_CALL_FAILURE';
