// import {svgIcons} from '../../assets/svgs/index';
export const appLogos = {};

export const appImages = {
  faceImg: require('../../assets/images/faceImg.png'),
  splashBg: require('../../assets/images/splashBg.png'),
  walk: require('../../assets/images/walk.png'),
  walkO: require('../../assets/images/walkO.png'),
  walk1: require('../../assets/images/walk1.png'),
  walk2: require('../../assets/images/walk2.png'),
  walk3: require('../../assets/images/walk3.png'),
  whiteTheme: require('../../assets/images/whiteTheme.png'),
  redTheme: require('../../assets/images/redTheme.png'),
  greenTheme: require('../../assets/images/greenTheme.png'),
  yellowTheme: require('../../assets/images/yellowTheme.png'),
  cosmicBlue: require('../../assets/images/cosmicBlue.png'),
  orangeTheme: require('../../assets/images/orangeTheme.png'),
  trans1: require('../../assets/images/trans1.png'),
  trans2: require('../../assets/images/trans2.png'),
};

export const appIcons = {
  RightArrow: require('../../assets/icons/arrowRight.png'),
  call: require('../../assets/icons/call.png'),
  apple: require('../../assets/icons/apple.png'),
  google: require('../../assets/icons/google.png'),
  facebook: require('../../assets/icons/facebook.png'),
  checkBox: require('../../assets/icons/checkBox.png'),
  UnCheckBox: require('../../assets/icons/UnCheckBox.png'),
  idFront: require('../../assets/icons/idFront.png'),
  idBack: require('../../assets/icons/idBack.png'),
  gallery: require('../../assets/icons/gallery.png'),
  themeCamera: require('../../assets/icons/themeCamera.png'),
  setting: require('../../assets/icons/setting.png'),
  userGroup: require('../../assets/icons/userGroup.png'),
  global: require('../../assets/icons/global.png'),
  world: require('../../assets/icons/world.png'),
  dial: require('../../assets/icons/dial.png'),
  document: require('../../assets/icons/Document.png'),
  star: require('../../assets/icons/Star.png'),
  group: require('../../assets/icons/group.png'),
  history: require('../../assets/icons/history.png'),
  profile: require('../../assets/icons/Profile.png'),
  call1: require('../../assets/icons/call1.png'),
  message: require('../../assets/icons/message.png'),
  video: require('../../assets/icons/video.png'),
  pencil: require('../../assets/icons/pencil.png'),
  bgProfile: require('../../assets/icons/bgProfile.png'),
  threeDots: require('../../assets/icons/threeDots.png'),
  video1: require('../../assets/icons/video1.png'),
  eng: require('../../assets/icons/eng.png'),
  caller: require('../../assets/icons/caller.png'),
  store: require('../../assets/icons/store.png'),
  delete: require('../../assets/icons/Delete.png'),
  wallet: require('../../assets/icons/wallet.png'),
  box: require('../../assets/icons/box.png'),
  fire: require('../../assets/icons/fire.png'),
  fire2: require('../../assets/icons/fire2.png'),
  label: require('../../assets/icons/label.png'),
  share: require('../../assets/icons/share.png'),
  privacy: require('../../assets/icons/privacy.png'),
  wallet1: require('../../assets/icons/wallet1.png'),
  gmessage: require('../../assets/icons/gmessage.png'),
  paper: require('../../assets/icons/paper.png'),
  share1: require('../../assets/icons/share1.png'),
  logout: require('../../assets/icons/logout.png'),
  user1: require('../../assets/icons/user1.png'),
  cards: require('../../assets/icons/cards.png'),
  loader: require('../../assets/icons/loader.png'),
  edit: require('../../assets/icons/edit.png'),
  happy: require('../../assets/icons/happy.png'),
  userGroup1: require('../../assets/icons/userGroup1.png'),
  wallet2: require('../../assets/icons/wallet2.png'),
  card: require('../../assets/icons/card.png'),
  googlewallet: require('../../assets/icons/googlewallet.png'),
  visa: require('../../assets/icons/visa.png'),
  visa1: require('../../assets/icons/visa1.png'),
  withdraw: require('../../assets/icons/withdraw.png'),
  transfer: require('../../assets/icons/transfer.png'),
  topUp: require('../../assets/icons/topUp.png'),
  addUser: require('../../assets/icons/addUser.png'),
  flower: require('../../assets/icons/flower.png'),
  tick: require('../../assets/icons/tick.png'),
  del: require('../../assets/icons/del.png'),
  edit1: require('../../assets/icons/edit1.png'),
  america: require('../../assets/icons/america.png'),
  bank: require('../../assets/icons/bank.png'),
  social: require('../../assets/icons/social.png'),
  camera1: require('../../assets/icons/camera1.png'),
  danger: require('../../assets/icons/danger.png'),
  send: require('../../assets/icons/send.png'),
  plus: require('../../assets/icons/plus.png'),
  lang: require('../../assets/icons/lang.png'),
  speaker: require('../../assets/icons/speaker.png'),
  pause: require('../../assets/icons/pause.png'),
  cutCall: require('../../assets/icons/cutCall.png'),
  play: require('../../assets/icons/play.png'),
  lock: require('../../assets/icons/lock.png'),
  flipCamera: require('../../assets/icons/flipCamera.png'),
  mute: require('../../assets/icons/mute.png'),
  unmute: require('../../assets/icons/unmute.png'),
  outgoing: require('../../assets/icons/outgoing.png'),
};

export const appSvgs = {
  // ...svgIcons,
};
export const appJSON = {
  playerIcon: require('../../assets/json/player.json'),
  playerIcon1: require('../../assets/json/player1.json'),
  soundWaves: require('../../assets/json/sound-waves.json'),
};
